[world]
name = "Abyss"
seed = "abyss-v0.1.5"

[namespace]
default = "ABYSS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0x010767a7837e1d4b2c8e499a87610d7b2f5f306f9a077b01bf2cded0b995cee0"
account_address = "0x05CC7fe1BfAAf3e05DFe1FD67397CeB3570D8869ddF96c5b5bC911289EeBa706"

[migration]
order_inits = [
  "ABYSS-Chip",
  "ABYSS-Charm",
  "ABYSS-RelicNFT",
  "ABYSS-Setup",
  "ABYSS-Collection",
  "ABYSS-Play",
  "ABYSS-Market",
  "ABYSS-Relic",
  "ABYSS-Treasury",
]
disable_multicall = true

[writers]
"ABYSS" = ["ABYSS-Setup", "ABYSS-Collection", "ABYSS-Play", "ABYSS-Market", "ABYSS-Relic", "ABYSS-Treasury"]

[owners]
"ABYSS" = ["ABYSS-Collection", "ABYSS-Chip", "ABYSS-RelicNFT"]


[init_call_args]
"ABYSS-Setup" = [
  "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
  "0x0512feac6339ff7889822cb5aa2a86c848e9d392bb0e3e237c008674feed8343", # quote_token (USDC)
  "0x05CC7fe1BfAAf3e05DFe1FD67397CeB3570D8869ddF96c5b5bC911289EeBa706", # team_address
]
