[world]
name = "Abyss"
seed = "abyss-v1.0.1"
description = "On chain version of the Abyss game."
website = "https://play.abyssgame.fun/"

[namespace]
default = "ABYSS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x019210e07e069cc67b17be1fbb2258411ddabf745ac32f22d0e547a61a8eceeb"
account_address = "0x39ca42b918d701ed01c50d2d5bebef9be78f80fe8d92170963523f8e0b532d9"

[migration]
order_inits = [
  "ABYSS-Chip",
  "ABYSS-Charm",
  "ABYSS-RelicNFT",
  "ABYSS-Setup",
  "ABYSS-Collection",
  "ABYSS-Play",
  "ABYSS-Market",
  "ABYSS-Relic",
  "ABYSS-Treasury",
]
disable_multicall = true

[writers]
"ABYSS" = ["ABYSS-Setup", "ABYSS-Collection", "ABYSS-Play", "ABYSS-Market", "ABYSS-Relic", "ABYSS-Treasury"]

[owners]
"ABYSS" = ["ABYSS-Collection", "ABYSS-Chip", "ABYSS-RelicNFT"]

[init_call_args]
"ABYSS-Setup" = [
  "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
  "0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb", # quote_token
  "0x07e89f628e2a133213443FE1b43dd0BB48ae3ab182f7B568A3fBDC6667041697", # team_address
]
